import React from "react";
import { DocsThemeConfig } from "nextra-theme-docs";

const config: DocsThemeConfig = {
  logo: <span>Haenu Docs</span>,
  project: {
    link: "https://github.com/dokdo2013/haenu-docs",
  },
  docsRepositoryBase: "https://github.com/dokdo2013/haenu-docs",
  footer: {
    text: "Generated by Nextra",
  },
};

export default config;
